version: 1.0.{build}
branches:
  only:
  - vs10
build_script:
- mkdir _vc10
- cd _vc10
- cmake -DCMAKE_MAKE_PROGRAM=C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe -G "Visual Studio 10" ..
- cmake --build .
notifications:
- provider: Email
  to:
  - doducthanhbk@gmail.com
  subject: Windows build broken
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false